<a href="https://colab.research.google.com/github/jeyanthi492/ML-projects/blob/main/CAR%20price%20prediction/CAR%20price%20prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CAR price prediction using Random forest regression & ENCODER

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving CarPrice_Assignment.csv to CarPrice_Assignment.csv


In [ ]:
dataset = pd.read_csv('CarPrice_Assignment.csv')

print(dataset.shape)
print(dataset.head(5))

(205, 26)
   car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm 

In [ ]:
dataset = dataset.drop(['car_ID'],axis=1)
print(dataset.shape)
print(dataset.head(5))

(205, 25)
   symboling                   CarName fueltype aspiration doornumber  \
0          3        alfa-romero giulia      gas        std        two   
1          3       alfa-romero stelvio      gas        std        two   
2          1  alfa-romero Quadrifoglio      gas        std        two   
3          2               audi 100 ls      gas        std       four   
4          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0  convertible        rwd          front       88.6      168.8  ...   
1  convertible        rwd          front       88.6      168.8  ...   
2    hatchback        rwd          front       94.5      171.2  ...   
3        sedan        fwd          front       99.8      176.6  ...   
4        sedan        4wd          front       99.4      176.6  ...   

   enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
0         130        mpfi       3.47   2.68     

In [ ]:
Xdata = dataset.drop('price',axis='columns')
numericalCols=Xdata.select_dtypes(exclude=['object']).columns
X=Xdata[numericalCols]
X

symboling  wheelbase  carlength  carwidth  carheight  curbweight  \
0            3       88.6      168.8      64.1       48.8        2548   
1            3       88.6      168.8      64.1       48.8        2548   
2            1       94.5      171.2      65.5       52.4        2823   
3            2       99.8      176.6      66.2       54.3        2337   
4            2       99.4      176.6      66.4       54.3        2824   
..         ...        ...        ...       ...        ...         ...   
200         -1      109.1      188.8      68.9       55.5        2952   
201         -1      109.1      188.8      68.8       55.5        3049   
202         -1      109.1      188.8      68.9       55.5        3012   
203         -1      109.1      188.8      68.9       55.5        3217   
204         -1      109.1      188.8      68.9       55.5        3062   

     enginesize  boreratio  stroke  compressionratio  horsepower  peakrpm  \
0           130       3.47    2.68               9.0         111     5000   
1           130       3.47    2.68               9.0         111     5000   
2           152       2.68    3.47               9.0         154     5000   
3           109       3.19    3.40              10.0         102     5500   
4           136       3.19    3.40               8.0         115     5500   
..          ...        ...     ...               ...         ...      ...   
200         141       3.78    3.15               9.5         114     5400   
201         141       3.78    3.15               8.7         160     5300   
202         173       3.58    2.87               8.8         134     5500   
203         145       3.01    3.40              23.0         106     4800   
204         141       3.78    3.15               9.5         114     5400   

     citympg  highwaympg  
0         21          27  
1         21          27  
2         19          26  
3         24          30  
4         18          22  
..       ...         ...  
200       23          28  
201       19          25  
202       18          23  
203       26          27  
204       19          25  

[205 rows x 14 columns]

In [ ]:
Y=dataset.price
#Y = dataset['price']
Y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...   
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [ ]:
from sklearn.preprocessing import scale
cols = X.columns
X = pd.DataFrame(scale(X)) # model should not give the importance to high value
X.columns = cols
X

symboling  wheelbase  carlength  carwidth  carheight  curbweight  \
0     1.743470  -1.690772  -0.426521 -0.844782  -2.020417   -0.014566   
1     1.743470  -1.690772  -0.426521 -0.844782  -2.020417   -0.014566   
2     0.133509  -0.708596  -0.231513 -0.190566  -0.543527    0.514882   
3     0.938490   0.173698   0.207256  0.136542   0.235942   -0.420797   
4     0.938490   0.107110   0.207256  0.230001   0.235942    0.516807   
..         ...        ...        ...       ...        ...         ...   
200  -1.476452   1.721873   1.198549  1.398245   0.728239    0.763241   
201  -1.476452   1.721873   1.198549  1.351515   0.728239    0.949992   
202  -1.476452   1.721873   1.198549  1.398245   0.728239    0.878757   
203  -1.476452   1.721873   1.198549  1.398245   0.728239    1.273437   
204  -1.476452   1.721873   1.198549  1.398245   0.728239    0.975021   

     enginesize  boreratio    stroke  compressionratio  horsepower   peakrpm  \
0      0.074449   0.519071 -1.839377         -0.288349    0.174483 -0.262960   
1      0.074449   0.519071 -1.839377         -0.288349    0.174483 -0.262960   
2      0.604046  -2.404880  0.685946         -0.288349    1.264536 -0.262960   
3     -0.431076  -0.517266  0.462183         -0.035973   -0.053668  0.787855   
4      0.218885  -0.517266  0.462183         -0.540725    0.275883  0.787855   
..          ...        ...       ...               ...         ...       ...   
200    0.339248   1.666445 -0.336970         -0.162161    0.250533  0.577692   
201    0.339248   1.666445 -0.336970         -0.364062    1.416637  0.367529   
202    1.109571   0.926204 -1.232021         -0.338824    0.757535  0.787855   
203    0.435538  -1.183483  0.462183          3.244916    0.047732 -0.683286   
204    0.339248   1.666445 -0.336970         -0.162161    0.250533  0.577692   

      citympg  highwaympg  
0   -0.646553   -0.546059  
1   -0.646553   -0.546059  
2   -0.953012   -0.691627  
3   -0.186865   -0.109354  
4   -1.106241   -1.273900  
..        ...         ...  
200 -0.340094   -0.400490  
201 -0.953012   -0.837195  
202 -1.106241   -1.128332  
203  0.119594   -0.546059  
204 -0.953012   -0.837195  

[205 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=10)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(164, 14) (41, 14) (164,) (41,)


In [ ]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train,y_train)

RandomForestRegressor()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([10305.66   , 19447.77167, 10953.94   , 11764.33   , 36934.25   ,
       10409.68   ,  7926.33   , 14869.54   ,  8219.3    , 19044.11   ,
       13051.53   , 10177.7    ,  7967.965  , 14203.57   , 36327.56   ,
       18667.89334,  9656.61   , 15802.2    , 12766.17   , 14865.17835,
        7424.5225 , 14851.49   , 10084.75   , 16756.51167, 18834.21   ,
       18278.32668,  9604.14   ,  8343.135  , 10087.63   , 19014.80167,
        7522.21   ,  7708.6    ,  6140.55   , 12794.92   , 27112.43   ,
       25325.99   , 14390.97   , 18916.91167, 10281.68   ,  5859.485  ,
       10315.15   ])

In [ ]:
from sklearn.metrics import r2_score
r2score = r2_score(y_test,y_pred)

print("R2Score",r2score*100)
r2score

R2Score 88.95344587612261


0.8895344587612262

In [ ]:
from sklearn.preprocessing import LabelEncoder
order = ['Low','Medium','High']
encoder = LabelEncoder()
encoder.fit(order)
data = ['Medium','Low','High','Medium']
encoded_data = encoder.transform(data)
print(encoded_data)

[2 1 0 2]


In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
data = [['Low'],['Medium'],['High']]
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
data = np.array(['Apple','Banana','Cherry','Apple','Cherry']).reshape(-1,1) #horizontal to vertical
encoder = OneHotEncoder(sparse=False)
encoded_data = encoder.fit_transform(data)
print("Original categories",encoder.categories_)
print("\n One hot encoded data:\n",encoded_data)

Original categories [array(['Apple', 'Banana', 'Cherry'], dtype='<U6')]

 One hot encoded data:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
